#
#	Global configuration for SNAP makefiles
#

GLIB = glib-core
SNAP = snap-core
SNAPADV = snap-adv

GLASGLIB=glasgow
EXLEMON=../../lemon/include

CGLIB = ../$(GLIB)
CSNAP = ../$(SNAP)

EXGLIB = ../../$(GLIB)
EXSNAP = ../../$(SNAP)
EXSNAPADV = ../../$(SNAPADV)

UNAME := $(shell uname)

ifeq ($(UNAME), Linux)
  # Linux flags
  CC = g++-9
  CXXFLAGS += -std=gnu++1y -Wall
  #CXXFLAGS += -std=gnu++2a -Wall
  CXXFLAGS += -O3 -DNDEBUG -fopenmp
  #CXXFLAGS += -O0 -DNDEBUG -fopenmp
  # turn on for crash debugging, get symbols with <prog> 2>&1 | c++filt
  #CXXFLAGS += -g -fsanitize=thread #-rdynamic -fsanitize=address 
  #CXXFLAGS += -ggdb
  # turn on for OpenMP
  CXXOPENMP = 
  LDFLAGS +=
  LIBS += -lrt 

else ifeq ($(UNAME), Darwin)
  # OS X flags
  CC = g++
  CXXFLAGS += -std=gnu++2a -Wall -Wno-unknown-pragmas # -Wextra -Wpedantic
  #CXXFLAGS += -std=gnu++1y -Wall -Wno-unknown-pragmas # -Wextra -Wpedantic
  CXXFLAGS += -O3 -DNDEBUG -pthread
  CLANG := $(shell g++ -v 2>&1 | grep clang | cut -d " " -f 2)
  ifneq ($(CLANG), LLVM)
    # CXXFLAGS += -fopenmp
    CXXFLAGS += -Xpreprocessor -fopenmp -lomp
    #CXXOPENMP += -fopenmp
  else
    CXXFLAGS += -Xpreprocessor -fopenmp -lomp
    #CXXOPENMP =
  endif
  LDFLAGS +=
  LIBS += -lemon
else ifeq ($(shell uname -o), Cygwin)
  # Cygwin flags
  CC = g++
  CXXFLAGS += -std=gnu++14 -Wall -D__STDC_LIMIT_MACROS
  CXXFLAGS += -O3 -DNDEBUG
  CXXOPENMP = -fopenmp
  LDFLAGS +=
  LIBS +=

endif

