#
# Makefile for non-Microsoft compilers
#

all: MakeAll

MakeAll:
#	$(MAKE) -C bt
#	$(MAKE) -C bt-parallel
#	$(MAKE) -C newapproach 
#	$(MAKE) -C staticsample 
#	$(MAKE) -C ex23
#	$(MAKE) -C ex23-parallel
#	$(MAKE) -C f23-parallel
	
clean:
#	$(MAKE) clean -C bt
#	$(MAKE) clean -C bt-parallel
#	$(MAKE) clean -C newapproach
#	$(MAKE) clean -C staticsample 
#	$(MAKE) clean -C ex23
#	$(MAKE) clean -C ex23-parallel
#	$(MAKE) clean -C f23-parallel
